Add invalidateSize
fis-sst/BlazorMaps pull request #2
Opened 2020-12-23 13:06 UTC by mithril52

I use Leaflet maps in a resizable container in my Blazor app. I needed the ability to call invalidateSize() when the container changes size so that leaflet will use the proper dimensions when knowing when to ask for more tiles.

Not sure if you are taking pull requests or not, but thought I would pass it on.

2021-01-04 10:29 UTC, mchilicki commented
Hi, thank you for your contribution. 
We implement BlazorMaps very closely connected to original Leaflet library, please see how `invalidateSize` is implemented in Leaflet. Can you correct your changes have one of parameters in a method, ZoomPanOptions or bool?

https://leafletjs.com/reference-1.7.1.html#map-methods-for-modifying-map-state
![image](https://user-images.githubusercontent.com/15014424/103525755-103ac700-4e80-11eb-9406-e5192a02075f.png)

2021-01-04 10:35 UTC, mchilicki requested changes

2021-01-04 10:35 UTC, mchilicki commented on FisSst.BlazorMaps/FisSst.BlazorMaps/Components/Map.razor.cs
> +        public async Task InvalidateSize()
Please add parameter bool or ZoomPanOptions

2021-01-04 10:38 UTC, mchilicki commented
Also please change your target branch to develop branch

2022-01-31 10:48 UTC, ledpup commented
It would be great to have this PR added in. I was looking for this on the weekend. We just hacked it in via javascript, but a Blazor command would be better.

2025-11-09 21:08 UTC, closed without merging